version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3004:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:3001/api

  backend:
    build:
      context: ./backend
    ports:
      - "3003:3001"
    environment:
      - NODE_ENV=production